# Outils de prétraitement des données



## Importation des libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importation du dataset

In [ ]:
dataset = pd.read_csv("/content/impactpauv.csv", encoding=('ISO-8859-1'))

In [ ]:
display(dataset)

milieu  taille  pauvre  sexecm  agecm  diplômcm  cmanalphabe  cmalphabe  \
0          1       5       2       1     44    3210.0            0          0   
1          1       6       2       1     48       NaN            0          0   
2          1       4       2       1     62       NaN            0          0   
3          1       2       2       0     33    2120.0            0          0   
4          1       2       2       1     34       NaN            0          0   
...      ...     ...     ...     ...    ...       ...          ...        ...   
4875       2       9       1       1     42       NaN            0          1   
4876       2       7       2       1     48       NaN            0          1   
4877       2       9       2       1     34       NaN            0          1   
4878       2      13       2       1     38       NaN            1          0   
4879       2       5       2       1     35       NaN            1          0   

      cm_prim  cm_coll  ...  cscm  typlog  nbpiece  stocp  deptot  region  \
0           0        0  ...     1       1        3      3   58422       1   
1           0        0  ...     0       1        3      3   49860       1   
2           0        1  ...     1       1        4      3   83743       1   
3           0        0  ...     0       1        3      1  148953       1   
4           0        0  ...     0       3        6      1  304798       1   
...       ...      ...  ...   ...     ...      ...    ...     ...     ...   
4875        0        0  ...     0       6        2      1   36371       8   
4876        0        0  ...     0       6        3      1   19266       8   
4877        0        0  ...     0       6        2      1   34710       8   
4878        0        0  ...     0       6        4      1   10771       8   
4879        0        0  ...     0       6        2      7   32711       8   

         coeffmen  ident   trmo          deppc  
0     1365.000000      1    0.0   11684.400391  
1     1164.800049      2    0.0    8310.000000  
2     1365.000000      3    0.0   20935.750000  
3     1589.900024      4  221.0   74476.500000  
4     1365.000000      5   78.0  152399.000000  
...           ...    ...    ...            ...  
4875  1584.699951   4876    0.0    4041.222168  
4876  1584.699951   4877    0.0    2752.285645  
4877  1584.699951   4878    0.0    3856.666748  
4878  1159.599976   4879    0.0     828.538452  
4879  1584.699951   4880    0.0    6542.200195  

[4880 rows x 24 columns]

In [ ]:
dataset.drop(['diplômcm','cmanalphabe','cmalphabe','cm_prim','cm_coll','cm_secon','cm_univ','cscm','nbpiece','deptot','region','coeffmen',
              'ident','trmo','deppc'],1,inplace=True)

In [ ]:
last_column = dataset.pop('pauvre') 
dataset.insert(8, 'pauvre', last_column) 
dataset.shape

(4880, 9)

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[ 1  5  1 ...  1  1  3]
 [ 1  6  1 ...  1  1  3]
 [ 1  4  1 ...  1  1  3]
 ...
 [ 2  9  1 ...  1  6  1]
 [ 2 13  1 ...  1  6  1]
 [ 2  5  1 ...  1  6  7]]


In [ ]:
print(y)

[2 2 2 ... 2 2 2]


## Splitting the dataset into the Training set and Test set 



In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_train)

[[1 8 1 ... 1 3 3]
 [1 5 1 ... 1 0 3]
 [1 3 1 ... 1 2 1]
 ...
 [1 4 1 ... 1 3 1]
 [1 4 0 ... 1 3 1]
 [1 4 1 ... 1 2 1]]


In [ ]:
print(X_train)

[[1 8 1 ... 1 3 3]
 [1 5 1 ... 1 0 3]
 [1 3 1 ... 1 2 1]
 ...
 [1 4 1 ... 1 3 1]
 [1 4 0 ... 1 3 1]
 [1 4 1 ... 1 2 1]]


## Feature Scaling (misesà échelles)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-0.87687917  0.72869297  0.45434314 ...  0.44693864 -0.65699767
   0.39598906]
 [-0.87687917 -0.32820512  0.45434314 ...  0.44693864 -2.17770057
   0.39598906]
 [-0.87687917 -1.03280385  0.45434314 ...  0.44693864 -1.16389863
  -0.54954079]
 ...
 [-0.87687917 -0.68050448  0.45434314 ...  0.44693864 -0.65699767
  -0.54954079]
 [-0.87687917 -0.68050448 -2.20097964 ...  0.44693864 -0.65699767
  -0.54954079]
 [-0.87687917 -0.68050448  0.45434314 ...  0.44693864 -1.16389863
  -0.54954079]]


In [ ]:
print(X_test)

[[ 1.14040797 -1.03280385  0.45434314 ...  0.44693864  1.3706062
  -0.54954079]
 [ 1.14040797  1.4332917   0.45434314 ...  0.44693864  0.86370523
  -0.54954079]
 [-0.87687917 -1.03280385  0.45434314 ...  0.44693864 -0.65699767
  -0.54954079]
 ...
 [-0.87687917  1.08099233 -2.20097964 ... -2.2374436  -0.65699767
  -0.54954079]
 [ 1.14040797  0.02409424  0.45434314 ...  0.44693864  0.86370523
  -0.54954079]
 [ 1.14040797  0.37639361  0.45434314 ...  0.44693864  0.86370523
  -0.54954079]]


## Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
#classifier.get_params()
coef = classifier.fit(X_train, y_train).coef_
intecept = classifier.fit(X_train, y_train).intercept_
print(coef, intecept)

[[-0.39603285  0.04935053 -0.00444662  0.0105353  -0.03410736 -0.07131528
  -0.13279128 -0.04390118]] [1.83091783]


## Predicting the Test set results

In [ ]:
y_pred = classifier.predict_proba(X_test)
print(y_pred)
y_pred_df = pd.DataFrame(y_pred[: ,1])
#print(y_pred_df)
y_test_pred = y_pred_df.applymap(lambda x:2 if x>=0.5 else 1)
#print(np.concatenate((y_test_pred, y_test.reshape(len(y_test),1)),1))
print(type(y_test))

from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
cm = confusion_matrix(y_test, y_test_pred)
print(cm)
print(accuracy_score(y_test, y_test_pred),"c-à-d :",accuracy_score(y_test, y_test_pred)*100,"%")
#print("acc_test",accuracy_score(y_test,y_pred))

[[0.24856007 0.75143993]
 [0.21396534 0.78603466]
 [0.09358075 0.90641925]
 ...
 [0.07142239 0.92857761]
 [0.22769395 0.77230605]
 [0.22236088 0.77763912]]
<class 'numpy.ndarray'>
[[  0 132]
 [  0 844]]
0.8647540983606558 c-à-d : 86.47540983606558 %
